# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon

default_job = "clippy"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--frozen", "--color", "always"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--frozen", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--all-targets", "--frozen", "--color", "always"]
need_stdout = true
watch = ["tests"]
