[package]
name = "rocketfetch"
version = "0.1.2"
authors = ["Devan Looches <devan.looches@gmail.com>"]
edition = "2018"
include = ["src/**/*"]
license = "MIT"
description = "A WIP command line system information tool written asynchronously in rust for performance with toml file configuration."
repository = "https://github.com/devanlooches/rustfetch"
readme = "README.md"

[dependencies]
console = {version = "0.14.1"}
dirs = {version = "3.0.2", default-features = false}
nixinfo = {version = "0.3.3", default-features = false}
regex = {version = "1.5.4", default-features = false, features = ["std", "unicode-perl"]}
rsys = {version = "0.5.5", default-features = false}
secfmt = {version = "0.1.1", default-features = false}
serde = {version = "1.0.126", default-features = false}
serde_derive = {version = "1.0.126", default-features = false}
structopt = {version = "0.3.21", default-features = false}
tokio = { version = "1.7.1",default-features = false, features = ["macros", "rt-multi-thread"] }
toml = {version = "0.5.8", default-features = false}
user-error = {version = "1.2.8", default-features = false}

[dev-dependencies]
pretty_assertions = {version = "0.7.2", default-features = false}
