[package]
name = "rocketfetch"
version = "0.5.7"
authors = ["Devan Looches <devan.looches@gmail.com>"]
edition = "2021"
include = ["src/**/*"]
license = "MIT"
description = "A WIP command line system information tool written asynchronously in rust for performance with toml file configuration."
repository = "https://github.com/devanlooches/rustfetch"
readme = "README.md"
keywords = ["system", "cli", "fetch", "asynchronous", "asynch"]
categories = ["command-line-utilities"]

[dependencies]
console = { version = "0.14.1", default-features = false, features = ["ansi-parsing"] }
dirs = { version = "4.0.0", default-features = false }
log = { version = "0.4.14", default-features = false }
nixinfo = { version = "0.3.3", default-features = false }
pest = { version = "2.1.3", default-features = false }
pest_derive = { version = "2.1.0", default-features = false }
regex = { version = "1.5.4", default-features = false, features = ["std", "unicode-perl"] }
rsys = { version = "0.5.5", default-features = false }
secfmt = { version = "0.1.1", default-features = false }
serde = { version = "1.0.130", default-features = false }
serde_derive = { version = "1.0.130", default-features = false }
simple_logger = { version = "1.13.0", default-features = false }
structopt = { version = "0.3.23", default-features = false }
tokio = { version = "1.12.0", default-features = false, features = ["macros", "rt-multi-thread"] }
toml = { version = "0.5.8", default-features = false }
user-error = { version = "1.2.8", default-features = false }

[dev-dependencies]
pretty_assertions = { version = "1.0.0", default-features = false }

[profile.release]
opt-level = 3
lto = "fat"
