[package]
name = "rocketfetch"
version = "0.6.12"
authors = ["Devan Looches <devan.looches@gmail.com>"]
edition = "2021"
include = ["src/**/*"]
license = "MIT"
description = "A WIP command line system information tool written asynchronously in rust for performance with toml file configuration."
repository = "https://github.com/devanlooches/rustfetch"
readme = "README.md"
keywords = ["system", "cli", "fetch", "multithreaded", "multithreading"]
categories = ["command-line-utilities"]

[dependencies]
any_terminal_size = { version = "0.1.21" }
console = { version = "0.15.2"}
dirs = { version = "4.0.0"}
libmacchina = { version = "6.3.1"}
regex = { version = "1.6.0"}
secfmt = { version = "0.1.1"}
serde = { version = "1.0.147"}
serde_derive = { version = "1.0.147"}
simple_logger = { version = "2.3.0"}
structopt = { version = "0.3.26"}
textwrap = { version = "0.15.2"}
toml = { version = "0.5.9"}
user-error = { version = "1.2.8"}

[dev-dependencies]
pretty_assertions = "1.3.0"
