module_order = "user delimiter os host kernel uptime packages shell resolution desktop_environment window_manager terminal"
offset = 4
logo_cmd = "auto"

[format]
mode = "classic"
top_left_corner_char = "╭"
top_right_corner_char = "╮"
bottom_left_corner_char = "╰"
bottom_right_corner_char = "╯"
horizontal_char = "─"
vertical_char = "│"
padding_left = 1
padding_right = 1
padding_top = 0

[user]
pre_text_style = "bold.yellow"
pre_text = ""
output_style = "bold.yellow"
separator_style = "white"
separator_char = "@"

[delimiter]
style = "white"
repeat_num = 0
char = "-"

[os]
pre_text_style = "bold.yellow"
pre_text = "OS: "
output_style = "white"

[host]
pre_text_style = "bold.yellow"
pre_text = "Host: "
output_style = "white"

[kernel]
pre_text_style = "bold.yellow"
pre_text = "Kernel: "
output_style = "white"

[uptime]
pre_text_style = "bold.yellow"
pre_text = "Uptime: "
output_style = "white"
time_format = "$days days, $hours hours, $minutes minutes"

[packages]
pre_text_style = "bold.yellow"
pre_text = "Packages: "
output_style = "white"

[shell]
pre_text_style = "bold.yellow"
pre_text = "Shell: "
output_style = "white"

[resolution]
pre_text_style = "bold.yellow"
pre_text = "Resolution: "
output_style = "white"

[desktop_environment]
pre_text_style = "bold.yellow"
pre_text = "Desktop Environment: "
output_style = "white"

[window_manager]
pre_text_style = "bold.yellow"
pre_text = "Window Manager: "
output_style = "white"

[terminal]
pre_text_style = "bold.yellow"
pre_text = "Terminal: "
output_style = "white"
