module_order = "user delimiter os host kernel uptime"
offset = 4
logo_cmd = "auto"

[format]
mode = "classic"
top_left_corner_char = "╭"
top_right_corner_char = "╮"
bottom_left_corner_char = "╰"
bottom_right_corner_char = "╯"
horizontal_char = "─"
vertical_char = "│"
padding_left = 1
padding_right = 1
padding_top = 0

[user]
pre_text_style = "bold.yellow"
pre_text = ""
output_style = "bold.yellow"
seperator_style = "white"
seperator_char = "@"

[delimiter]
style = "white"
repeat_num = 0
char = "-"

[os]
pre_text_style = "bold.yellow"
pre_text = "OS: "
output_style = "white"

[host]
pre_text_style = "bold.yellow"
pre_text = "Host: "
output_style = "white"

[kernel]
pre_text_style = "bold.yellow"
pre_text = "Kernel: "
output_style = "white"

[uptime]
pre_text_style = "bold.yellow"
pre_text = "Uptime: "
output_style = "white"
time_format = "$days days, $hours hours, $minutes minutes"
