name: Release Binaries

permissions:
  contents: write

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        id: latest-tag
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          ref: refs/tags/${{ steps.latest-tag.outputs.tag }}
          bin: rocketfetch
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: $bin-$target-$tag
